In [217]:
import numpy as np
import pandas as pd                   #Feature Selection For ML Model From Given Dataset
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import mode
from sklearn.model_selection import train_test_split

df=pd.read_csv("results.csv")  #Importing Dataset
df1=pd.read_csv("results.csv")
df.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban,Y
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban,Y
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban,Y
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban,Y
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban,Y
5,LP001054,Male,Yes,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.0,Urban,Y
6,LP001055,Female,No,1,Not Graduate,No,2226,0,59.0,360.0,1.0,Semiurban,Y
7,LP001056,Male,Yes,2,Not Graduate,No,3881,0,147.0,360.0,0.0,Rural,N
8,LP001059,Male,Yes,2,Graduate,NaN,13633,0,280.0,240.0,1.0,Urban,Y
9,LP001067,Male,No,0,Not Graduate,No,2400,2400,123.0,360.0,1.0,Semiurban,Y

In [201]:
from sklearn.preprocessing import LabelEncoder      #Use Label Encoding to convert categorical data into numeric
la = LabelEncoder()
label_encoder_arr={}
for i in df1.select_dtypes(include=['object']).columns:
 la = LabelEncoder()
 df1[i]=la.fit_transform(df1[i])
 label_encoder_arr[i] = la

In [203]:
for col in df1.select_dtypes(include='number').columns:      #Filling Null Values In Whole Dataset
    df1[col] = df1[col].fillna(df1[col].mean())

In [204]:

from sklearn.model_selection import train_test_split

# Ensure the split is correct: 80% for training, 20% for testing
X = df1.drop('Loan_Status', axis=1)  # Ensure the target column is dropped
y = df1['Loan_Status']

# Split the data correctly:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Check if the split is now correct
print("Length of X_train:", len(X_train))
print("Length of X_test:", len(X_test))
print("Length of df:", len(df1))

Length of X_train: 293
Length of X_test: 74
Length of df: 367

In [205]:
print("Number of duplicate rows in df:", df.duplicated().sum())

# Optionally, drop duplicates
df1 = df1.drop_duplicates()

Number of duplicate rows in df: 0

In [206]:
from sklearn.preprocessing import StandardScaler


#Scaling Data to put Dataset in Normal Distribution
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [228]:
from sklearn.ensemble import BaggingClassifier

In [229]:
from sklearn.linear_model import LogisticRegression

In [230]:
#Using Bagging Concept to combine predictions from multiple models trained on different subsets of the data,
bc=BaggingClassifier(n_estimators=50)
bc.fit(X_train,y_train)
print("Training Accuracy: ",bc.score(X_train, y_train)*100)
print("Testing Accuracy: ",bc.score(X_test, y_test)*100)

Training Accuracy:  100.0
Testing Accuracy:  94.5945945945946

In [231]:
# Make predictions on the test data
predictions = bc.predict(X_test)
df.loc[X_test.index, 'Predicted_Loan_Status'] = predictions

In [225]:
print("Length of df:", len(df))
print("Length of X_train:", len(df['Predicted_Loan_Status']))
print("Length of X_test:", len(X_test))

Length of df: 367
Length of X_train: 367
Length of X_test: 74

In [226]:
# Prediction Analysis using classification report
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      0.86      0.93        22
           1       0.95      1.00      0.97        52

    accuracy                           0.96        74
   macro avg       0.97      0.93      0.95        74
weighted avg       0.96      0.96      0.96        74

In [232]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Predicted_Loan_Status
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban,Y,1.0
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban,Y,1.0
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban,Y,1.0
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban,Y,1.0
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban,Y,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,Urban,Y,1.0
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,Urban,Y,1.0
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,NaN,Semiurban,Y,1.0
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,Rural,Y,1.0
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,Rural,Y,1.0